# This file was automatically generated by tools/build/create_api.py.
# Do not edit.
"""Predefined deep learning models for various tasks."""

from im2sim.src.layers.halfunet import HalfUNet as HalfUNet
