# This file was automatically generated by tools/build/create_api.py.
# Do not edit.
"""Custom loss functions for training deep learning models."""

from im2sim.src.losses.confusion_losses import FocalTverskyLoss as FocalTverskyLoss
from im2sim.src.losses.confusion_losses import TverskyLoss as TverskyLoss
from im2sim.src.losses.confusion_losses import DiceLoss as DiceLoss
from im2sim.src.losses.confusion_losses import IoULoss as IoULoss
from im2sim.src.losses.ssim import SSIMLoss as SSIMLoss
