# This file was automatically generated by tools/build/create_api.py.
# Do not edit.
"""IM2SIM."""
import os as _os
import sys as _sys

from im2sim.__about__ import *

# Import submodules.
from im2sim._api import data
from im2sim._api import layers
from im2sim._api import configs
from im2sim._api import ops
from im2sim._api import losses
from im2sim._api import models
from im2sim._api import plot
from im2sim._api import _internal

# Make sure directory containing top level submodules is in
# the __path__ so that "from tensorflow_mri.foo import bar" works.
# We're using callbacks, but there's nothing special about that.
_API_MODULE = _sys.modules[__name__].layers
_im2sim_api_dir = _os.path.dirname(_os.path.dirname(_API_MODULE.__file__))
_current_module = _sys.modules[__name__]

if not hasattr(_current_module, '__path__'):
  __path__ = [_im2sim_api_dir]
elif _im2sim_api_dir not in __path__:
  __path__.append(_im2sim_api_dir)
