# This file was automatically generated by tools/build/create_api.py.
# Do not edit.
"""Configuration classes for model and training settings."""

from im2sim.src.layers.image_conv_blocks import ImageConvBlockConfig as ImageConvBlockConfig
from im2sim.src.layers.halfunet import HalfUNetConfig as HalfUNetConfig
