# This file was automatically generated by tools/build/create_api.py.
# Do not edit.
"""Internal utilities and functions for development and testing purposes."""

from im2sim.src.layers.module_config import Config as Config
from im2sim.src.layers.module_config import register_config as register_config
