name: Build API

on:
  push:
  pull_request:
    paths:
      - "tools/**"
      - "src/**"

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -e 